services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: TestWebApplication
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"